{
 "title": "Golden Signals Dashboard",
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(otel_collector_span_metrics_duration_milliseconds_bucket[5m])) by (span_name)",
     "legendFormat": "{{`{{ span_name }}`}}"
    }
   ]
  },
  {
   "title": "Traffic (Receive Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 9, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total[5m])) by (container_label_k8s_app)",
     "legendFormat": "{{`{{ container_label_k8s_app }}`}}"
    }
   ]
  },
  {
   "title": "Traffic (Transmit Bytes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 9, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total[5m])) by (container_label_k8s_app)",
     "legendFormat": "{{`{{ container_label_k8s_app }}`}}"
    }
   ]
  },
  {
   "title": "Traffic (Receive Errors)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 18, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_errors_total[5m])) by (container_label_k8s_app)",
     "legendFormat": "{{`{{ container_label_k8s_app }}`}}"
    }
   ]
  },
  {
   "title": "Traffic (Transmit Errors)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 18, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_errors_total[5m])) by (container_label_k8s_app)",
     "legendFormat": "{{`{{ container_label_k8s_app }}`}}"
    }
   ]
  },
  {
   "title": "Errors (Container Scrape Error)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 27, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_scrape_error[5m])) by (job)",
     "legendFormat": "{{`{{ job }}`}}"
    }
   ]
  },
  {
   "title": "Errors (Application Logs)",
   "type": "logs",
   "gridPos": { "x": 0, "y": 36, "w": 24, "h": 8 },
   "targets": [
    {
     "expr": "{service_name=\"unknown_service\"} |= `err`",
     "legendFormat": "{{`{{ service_name }}`}}"
    }
   ]
  },
  {
   "title": "Saturation (CPU Usage)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 45, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_system_seconds_total[5m])) by (container_label_io_kubernetes_container_name)",
     "legendFormat": "{{`{{ container_label_io_kubernetes_container_name }}`}}"
    }
   ]
  },
  {
   "title": "Saturation (Filesystem Writes)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 45, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_fs_writes_bytes_total[5m])) by (container_label_io_kubernetes_container_name)",
     "legendFormat": "{{`{{ container_label_io_kubernetes_container_name }}`}}"
    }
   ]
  }
 ]
}